# Project: Management_System
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o password.o
LINKOBJ  = main.o password.o
LIBS     = -L"D:/DEV_C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -pg
INCS     = -I"D:/DEV_C++/Dev-Cpp/MinGW64/include" -I"D:/DEV_C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DEV_C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/DEV_C++/Dev-Cpp/MinGW64/include" -I"D:/DEV_C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DEV_C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/DEV_C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Management_System.exe
CXXFLAGS = $(CXXINCS) -m32 -pg
CFLAGS   = $(INCS) -m32 -pg
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

password.o: password.c
	$(CC) -c password.c -o password.o $(CFLAGS)
